/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RecentDevelopmentInput = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
});
export const RecentDevelopment = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const categoryTypeEnum = IDL.Variant({
  'money' : IDL.Null,
  'neighborhood' : IDL.Null,
  'divorce' : IDL.Null,
  'employment' : IDL.Null,
  'business' : IDL.Null,
  'consumer' : IDL.Null,
  'property' : IDL.Null,
  'family' : IDL.Null,
});
export const DisputeCategory = IDL.Record({
  'isMediationSuitable' : IDL.Bool,
  'title' : IDL.Text,
  'legalAdvice' : IDL.Text,
  'description' : IDL.Text,
  'categoryTypeEnum' : categoryTypeEnum,
  'mediationReason' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DoAndDont = IDL.Record({
  'dos' : IDL.Vec(IDL.Text),
  'donts' : IDL.Vec(IDL.Text),
});
export const DisputeSpecificGuidance = IDL.Record({
  'nextSteps' : IDL.Vec(IDL.Text),
  'dosAndDonts' : DoAndDont,
  'legalInformation' : IDL.Text,
  'mediationSuitabilityGuidance' : IDL.Text,
  'contextSpecificExamples' : IDL.Vec(IDL.Text),
});
export const GuidanceResult = IDL.Record({
  'category' : DisputeCategory,
  'fullDispute' : DisputeSpecificGuidance,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDevelopment' : IDL.Func(
      [RecentDevelopmentInput],
      [RecentDevelopment],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'editDevelopment' : IDL.Func(
      [IDL.Nat, RecentDevelopmentInput],
      [RecentDevelopment],
      [],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(DisputeCategory)], ['query']),
  'getAllDevelopments' : IDL.Func([], [IDL.Vec(RecentDevelopment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGuidanceByCategory' : IDL.Func(
      [categoryTypeEnum],
      [IDL.Opt(GuidanceResult)],
      ['query'],
    ),
  'getGuidanceByDescription' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'confidence' : IDL.Nat8,
          'guidance' : IDL.Opt(GuidanceResult),
          'bestMatch' : IDL.Opt(DisputeCategory),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RecentDevelopmentInput = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
  });
  const RecentDevelopment = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const categoryTypeEnum = IDL.Variant({
    'money' : IDL.Null,
    'neighborhood' : IDL.Null,
    'divorce' : IDL.Null,
    'employment' : IDL.Null,
    'business' : IDL.Null,
    'consumer' : IDL.Null,
    'property' : IDL.Null,
    'family' : IDL.Null,
  });
  const DisputeCategory = IDL.Record({
    'isMediationSuitable' : IDL.Bool,
    'title' : IDL.Text,
    'legalAdvice' : IDL.Text,
    'description' : IDL.Text,
    'categoryTypeEnum' : categoryTypeEnum,
    'mediationReason' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DoAndDont = IDL.Record({
    'dos' : IDL.Vec(IDL.Text),
    'donts' : IDL.Vec(IDL.Text),
  });
  const DisputeSpecificGuidance = IDL.Record({
    'nextSteps' : IDL.Vec(IDL.Text),
    'dosAndDonts' : DoAndDont,
    'legalInformation' : IDL.Text,
    'mediationSuitabilityGuidance' : IDL.Text,
    'contextSpecificExamples' : IDL.Vec(IDL.Text),
  });
  const GuidanceResult = IDL.Record({
    'category' : DisputeCategory,
    'fullDispute' : DisputeSpecificGuidance,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDevelopment' : IDL.Func(
        [RecentDevelopmentInput],
        [RecentDevelopment],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'editDevelopment' : IDL.Func(
        [IDL.Nat, RecentDevelopmentInput],
        [RecentDevelopment],
        [],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(DisputeCategory)], ['query']),
    'getAllDevelopments' : IDL.Func(
        [],
        [IDL.Vec(RecentDevelopment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGuidanceByCategory' : IDL.Func(
        [categoryTypeEnum],
        [IDL.Opt(GuidanceResult)],
        ['query'],
      ),
    'getGuidanceByDescription' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'confidence' : IDL.Nat8,
            'guidance' : IDL.Opt(GuidanceResult),
            'bestMatch' : IDL.Opt(DisputeCategory),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };