/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DisputeCategory {
  'isMediationSuitable' : boolean,
  'title' : string,
  'legalAdvice' : string,
  'description' : string,
  'categoryTypeEnum' : categoryTypeEnum,
  'mediationReason' : string,
}
export interface DisputeSpecificGuidance {
  'nextSteps' : Array<string>,
  'dosAndDonts' : DoAndDont,
  'legalInformation' : string,
  'mediationSuitabilityGuidance' : string,
  'contextSpecificExamples' : Array<string>,
}
export interface DoAndDont { 'dos' : Array<string>, 'donts' : Array<string> }
export interface GuidanceResult {
  'category' : DisputeCategory,
  'fullDispute' : DisputeSpecificGuidance,
}
export interface RecentDevelopment {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'date' : bigint,
  'description' : string,
}
export interface RecentDevelopmentInput {
  'url' : string,
  'title' : string,
  'date' : bigint,
  'description' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type categoryTypeEnum = { 'money' : null } |
  { 'neighborhood' : null } |
  { 'divorce' : null } |
  { 'employment' : null } |
  { 'business' : null } |
  { 'consumer' : null } |
  { 'property' : null } |
  { 'family' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDevelopment' : ActorMethod<[RecentDevelopmentInput], RecentDevelopment>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'editDevelopment' : ActorMethod<
    [bigint, RecentDevelopmentInput],
    RecentDevelopment
  >,
  'getAllCategories' : ActorMethod<[], Array<DisputeCategory>>,
  'getAllDevelopments' : ActorMethod<[], Array<RecentDevelopment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGuidanceByCategory' : ActorMethod<
    [categoryTypeEnum],
    [] | [GuidanceResult]
  >,
  'getGuidanceByDescription' : ActorMethod<
    [string],
    {
      'confidence' : number,
      'guidance' : [] | [GuidanceResult],
      'bestMatch' : [] | [DisputeCategory],
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];